# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.

name: "Tests"

on:
  push:
    branches: [main, main-rails]
  pull_request:
    branches: [main, main-rails]
  merge_group:
    types: [checks_requested]
permissions:
  contents: read
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: "test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        # The ruby version is taken from the .ruby-version file, no need to specify here.
        uses: ruby/setup-ruby@df99e806d4462b1b0f1d13061fa63fce294b3d46
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # Add or replace test runners here
      - name: Run Ruby tests
        run: bundle exec rspec
